### PR TITLE
Synchronization with java_client v3.0

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
Java samles have been synchronized with java_client v3.0

### CODE REVIEW

**Comment by Jonahss** [comment]
Rather than MobileElement, I think sometimes we want IOSElement or AndroidElement. because certain methods are only available on each.

**Comment by TikhomirovSergey** [comment]
Ok! I'll add these exampes

**Comment by TikhomirovSergey** [comment]
Samples were updated. Now they demostrate how to use AndroidElement/IOSElement with generic AppiumDriver.

**Comment by Jonahss** [comment]
great!

**Pull request merged**
